# 넘파이 Numpy

## numpy as np

In [2]:
# numpy
import numpy as np
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]

In [6]:
arr1 = np.array(data1)
arr2 = np.array(data2)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [8]:
arr1.shape , arr1.dtype

((5,), dtype('int64'))

In [9]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3.shape, arr3.dtype

((2, 3), dtype('int64'))

In [14]:
zz = np.zeros(10)
zz, zz.shape , zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [16]:
zzz = np.zeros((3,5))
zzz, zzz.shape, zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [17]:
oo = np.ones(7)
oo , oo.shape , oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [19]:
ooo = np.ones((2,10))
ooo, ooo.shape, ooo.dtype

(array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 (2, 10),
 dtype('float64'))

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.array 연산

In [22]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [24]:
print(arr1.shape , arr1.dtype)
print(arr2.shape , arr2.dtype)

(2, 3) int64
(2, 3) int64


In [ ]:
#브로드캐스트 : 같은 크기의 배열을 가지지 않아도 요소별 연산이 가능함
result0 = arr1 * 3
result1 = arr1 + arr2
result2 = arr1 - arr2
result3 = arr1*2 - arr2/10
result4 = arr1 * arr2
result5 = arr1 / arr2

arr3 = np.array([22,33,44])
print(result0)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(arr1 + arr3)
print(arr1 * arr3)
print(arr1 * arr3)
print(arr1 * arr3)


[[ 3  6  9]
 [12 15 18]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]
[[23 35 47]
 [26 38 50]]
[[ 22  66 132]
 [ 88 165 264]]


# 1차원

In [42]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
#size : 배열의 원소 총 개수
# ndim : 축의 개수
arr = np.arange(5)
arr, arr.shape, arr.dtype, arr.size, arr.ndim

(array([0, 1, 2, 3, 4]), (5,), dtype('int64'), 5, 1)

In [44]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4], dtype='str')
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [56]:
arr4 = np.full((2,4),"없어")
arr4
arr5 = np.eye(3)
arr5
arr6 = np.linspace(0,100,5, endpoint=False, dtype="int64")
print(arr6)
arr7 = np.arange(0,100,20)
print(arr7)

[ 0 20 40 60 80]
[ 0 20 40 60 80]


# 2차원

In [61]:
arr20 = np.array([[1,2],[3,4]])
arr20, arr20.shape, arr20.size, arr20.dtype, arr20.ndim, type(arr20)

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 4,
 dtype('int64'),
 2,
 numpy.ndarray)

In [70]:
try:
    arr21 = np.arange(1,10).reshape(3,3)
    print(arr21, arr21.shape, arr21.size, arr21.dtype, arr21.ndim, type(arr21))
    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22, arr22.shape, arr22.size, arr22.dtype, arr22.ndim, type(arr22))
    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23, arr23.shape, arr23.size, arr23.dtype, arr23.ndim, type(arr23))

except valueError as e:
    print("차원과 사이즈가 맞지 않습니다:", e)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] (3, 6) 18 int64 2 <class 'numpy.ndarray'>


# 인덱싱(마스크)

In [3]:
import numpy as np
# 난수 발생
ran_data = np.random.rand(8,4)
ran_data


array([[0.42474149, 0.35630014, 0.19823845, 0.07465194],
       [0.59652731, 0.53608019, 0.43549175, 0.57622032],
       [0.1582038 , 0.29669173, 0.79024675, 0.77664473],
       [0.63978449, 0.43361373, 0.83626797, 0.61882403],
       [0.68404728, 0.48540934, 0.95497535, 0.19972908],
       [0.5075166 , 0.20845393, 0.33339688, 0.83183127],
       [0.16955809, 0.08786892, 0.15466195, 0.55607514],
       [0.99293957, 0.19247509, 0.51819953, 0.56672228]])

In [4]:
mask = np.array([True,False,True,False,False,True,True,False])
mask

array([ True, False,  True, False, False,  True,  True, False])

In [5]:
ran_data[mask]

array([[0.42474149, 0.35630014, 0.19823845, 0.07465194],
       [0.1582038 , 0.29669173, 0.79024675, 0.77664473],
       [0.5075166 , 0.20845393, 0.33339688, 0.83183127],
       [0.16955809, 0.08786892, 0.15466195, 0.55607514]])

In [6]:
fruit = np.array(['apple', 'banana','apple', 'kiwi', 'orange', 'apple', 'apple', 'melon'])
fruit

array(['apple', 'banana', 'apple', 'kiwi', 'orange', 'apple', 'apple',
       'melon'], dtype='<U6')

In [7]:
fruit_mask = ( fruit == 'apple')
fruit_mask

array([ True, False,  True, False, False,  True,  True, False])

In [8]:
ran_data[fruit_mask]

array([[0.42474149, 0.35630014, 0.19823845, 0.07465194],
       [0.1582038 , 0.29669173, 0.79024675, 0.77664473],
       [0.5075166 , 0.20845393, 0.33339688, 0.83183127],
       [0.16955809, 0.08786892, 0.15466195, 0.55607514]])

In [10]:
ran_data[(fruit == 'apple') | (fruit == 'orange'),1:-1] # ran_data [행,열]

array([[0.35630014, 0.19823845],
       [0.29669173, 0.79024675],
       [0.48540934, 0.95497535],
       [0.20845393, 0.33339688],
       [0.08786892, 0.15466195]])

## 인덱스와 마스크의 응용

In [30]:
ran_data[:,0] > 0

array([False, False,  True,  True,  True, False, False,  True])

In [31]:
ran_data[ran_data[:,:] > 0]

array([1.52338002, 0.56841173, 1.48479825, 0.0472748 , 0.89554401,
       1.03181096, 0.40603421, 2.04825109, 1.64156327, 0.41446306,
       1.36649528, 1.84184625, 0.21090229, 0.09102871, 1.76516235,
       0.90448078, 1.0191247 , 0.1352295 , 0.4699508 , 0.08636828,
       0.7879186 , 0.30455091, 0.53760887, 0.88900879])

In [42]:
# ran_data에서 # 5번째 열의 값이 0보다 작은 행의 2,3번째 열의 값만 추출하라.

import numpy as np
ran_data = np.random.randn(8, 6)

# 조건: 5번째 열(index 4)이 0보다 작은 행
mask = ran_data[:, 4] < 0

# 해당 행의 2,3번째 열(index 1,2) 값만 추출
selected_values = ran_data[mask, 1:3]

print("원본 데이터:\n", ran_data)
print("\n조건에 맞는 행의 2,3번째 열 값:\n", selected_values)


원본 데이터:
 [[-0.58006643 -0.02319728 -0.03157435  0.58753531 -0.99167641  2.15228246]
 [-0.73577306  0.03243273 -0.51929168 -0.44161097  0.54050596 -0.91169575]
 [ 0.92803577  1.20754229 -0.40687514 -2.01076716  0.38296131  0.38944797]
 [-0.03084979 -0.26332182 -0.49026573 -1.22356041 -0.67102793  0.57013874]
 [-1.09238579 -1.1029634  -0.65986587  0.23830226 -0.55950328  1.04138065]
 [ 1.54566149  1.12504029 -0.50342678  1.45120795  0.97741655 -0.65906609]
 [ 0.53071793 -0.51939155 -0.68847499 -0.50400184  0.24016443  0.0236934 ]
 [-0.40897998  1.63375874 -1.66873722 -0.90504235  0.86272109  0.33544444]]

조건에 맞는 행의 2,3번째 열 값:
 [[-0.02319728 -0.03157435]
 [-0.26332182 -0.49026573]
 [-1.1029634  -0.65986587]]


In [50]:
ran_data = np.random.randn(8,4)
ran_data = [ran_data[:0] < 0,2:4] = np.nan # np.nan
ran_data

SyntaxError: invalid syntax (1215518198.py, line 2)

In [51]:
ran_data[~np.isnan(ran_data). any(axis=1)]
ran_data


array([[-0.58006643, -0.02319728, -0.03157435,  0.58753531, -0.99167641,
         2.15228246],
       [-0.73577306,  0.03243273, -0.51929168, -0.44161097,  0.54050596,
        -0.91169575],
       [ 0.92803577,  1.20754229, -0.40687514, -2.01076716,  0.38296131,
         0.38944797],
       [-0.03084979, -0.26332182, -0.49026573, -1.22356041, -0.67102793,
         0.57013874],
       [-1.09238579, -1.1029634 , -0.65986587,  0.23830226, -0.55950328,
         1.04138065],
       [ 1.54566149,  1.12504029, -0.50342678,  1.45120795,  0.97741655,
        -0.65906609],
       [ 0.53071793, -0.51939155, -0.68847499, -0.50400184,  0.24016443,
         0.0236934 ],
       [-0.40897998,  1.63375874, -1.66873722, -0.90504235,  0.86272109,
         0.33544444]])

In [52]:
fix_data[~np.isnan(ran_data). any(axis=1)]
fix_data


NameError: name 'fix_data' is not defined

In [53]:
np.sign(ran_data)

array([[-1., -1., -1.,  1., -1.,  1.],
       [-1.,  1., -1., -1.,  1., -1.],
       [ 1.,  1., -1., -1.,  1.,  1.],
       [-1., -1., -1., -1., -1.,  1.],
       [-1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1.,  1., -1.],
       [ 1., -1., -1., -1.,  1.,  1.],
       [-1.,  1., -1., -1.,  1.,  1.]])

In [ ]:
# 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)
np.cos(ran_data)

array([[ 0.83642624,  0.99973096,  0.99950157,  0.83230941,  0.54728757,
        -0.54926643],
       [ 0.74131213,  0.99947411,  0.86817091,  0.90406432,  0.85744844,
         0.61240606],
       [ 0.59940739,  0.3553178 ,  0.91836194, -0.42591308,  0.92756216,
         0.92511879],
       [ 0.99952418,  0.96553067,  0.88220777,  0.3403    ,  0.78318292,
         0.8418261 ],
       [ 0.46036875,  0.45095313,  0.79007446,  0.97174013,  0.84751886,
         0.50502909],
       [ 0.02513219,  0.43114016,  0.87593453,  0.11930354,  0.55916624,
         0.79056448],
       [ 0.86244391,  0.86812134,  0.77221584,  0.87565696,  0.97129888,
         0.99971932],
       [ 0.91752694, -0.06292082, -0.09778439,  0.61765228,  0.6503729 ,
         0.9442641 ]])

In [55]:
# 두 개의 array에 동일한 위치의 요소끼리 비교하기
data1 = np.random.randn(8,4)
data2 = np.random.randn(8,4)
data1, data2

(array([[-0.7518965 , -1.09235967,  0.19425123, -0.05097728],
        [-0.52084556, -0.51854149, -0.80990122,  1.20364918],
        [ 1.5814422 ,  0.25463986, -0.07930324, -0.42937974],
        [ 0.42003631,  2.27250887, -1.30572387, -0.41567174],
        [ 0.26494214,  1.24958849,  0.3843121 ,  0.90409841],
        [-2.59697807,  0.58467607, -1.13859989, -1.8813794 ],
        [-0.06299072,  0.8816878 ,  0.06339213,  0.00607717],
        [-0.3788946 ,  0.81926452, -1.30327613, -2.60025542]]),
 array([[ 1.26586885,  0.2908186 ,  0.90249477, -1.23647837],
        [-0.54097193, -2.34789356,  0.69898667, -0.21868747],
        [ 0.61193676, -0.15818585, -1.03268254, -1.60805084],
        [-0.11296835, -1.31832079,  1.1104013 , -0.83307873],
        [-0.93534639,  0.23588687, -1.66509683,  0.57406411],
        [-0.48370208, -1.50812683, -0.67383851,  1.64926565],
        [-0.82697897,  0.90237936, -0.34493705,  0.03855306],
        [ 1.40474593,  0.34737052,  0.15017422, -0.56566115]]))

In [57]:
np.maximum(data1,data2)

array([[ 1.26586885,  0.2908186 ,  0.90249477, -0.05097728],
       [-0.52084556, -0.51854149,  0.69898667,  1.20364918],
       [ 1.5814422 ,  0.25463986, -0.07930324, -0.42937974],
       [ 0.42003631,  2.27250887,  1.1104013 , -0.41567174],
       [ 0.26494214,  1.24958849,  0.3843121 ,  0.90409841],
       [-0.48370208,  0.58467607, -0.67383851,  1.64926565],
       [-0.06299072,  0.90237936,  0.06339213,  0.03855306],
       [ 1.40474593,  0.81926452,  0.15017422, -0.56566115]])

In [60]:
np.minimum(data1,data2)

array([[-0.7518965 , -1.09235967,  0.19425123, -1.23647837],
       [-0.54097193, -2.34789356, -0.80990122, -0.21868747],
       [ 0.61193676, -0.15818585, -1.03268254, -1.60805084],
       [-0.11296835, -1.31832079, -1.30572387, -0.83307873],
       [-0.93534639,  0.23588687, -1.66509683,  0.57406411],
       [-2.59697807, -1.50812683, -1.13859989, -1.8813794 ],
       [-0.82697897,  0.8816878 , -0.34493705,  0.00607717],
       [-0.3788946 ,  0.34737052, -1.30327613, -2.60025542]])

In [61]:
np.maximum(data1, 0) # reLu(x) 같다.


array([[0.        , 0.        , 0.19425123, 0.        ],
       [0.        , 0.        , 0.        , 1.20364918],
       [1.5814422 , 0.25463986, 0.        , 0.        ],
       [0.42003631, 2.27250887, 0.        , 0.        ],
       [0.26494214, 1.24958849, 0.3843121 , 0.90409841],
       [0.        , 0.58467607, 0.        , 0.        ],
       [0.        , 0.8816878 , 0.06339213, 0.00607717],
       [0.        , 0.81926452, 0.        , 0.        ]])

In [63]:
np.minimum(np.maximum(data2,0.5),1.7)

array([[1.26586885, 0.5       , 0.90249477, 0.5       ],
       [0.5       , 0.5       , 0.69898667, 0.5       ],
       [0.61193676, 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 1.1104013 , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.57406411],
       [0.5       , 0.5       , 0.5       , 1.64926565],
       [0.5       , 0.90237936, 0.5       , 0.5       ],
       [1.40474593, 0.5       , 0.5       , 0.5       ]])

## 통계함수

In [104]:
data = np.random.randn(4,4)
data

array([[ 1.13257798, -0.34133498, -1.28416748,  1.02549034],
       [-0.13827764, -0.00589804,  0.1374056 , -0.92528304],
       [ 1.7482227 ,  0.06961901, -0.59151631,  0.30202178],
       [ 0.26117136,  0.31666585,  0.19654439,  0.53773203]])

In [105]:
np.sum(data, axis=0)

array([ 3.0036944 ,  0.03905184, -1.54173381,  0.93996111])

In [106]:
np.sum(data, axis=1)

array([ 0.53256586, -0.93205313,  1.52834719,  1.31211363])

In [108]:
np.sum(data[:,1:3], axis=1)

array([-1.62550246,  0.13150755, -0.5218973 ,  0.51321024])

In [109]:
data2 = np.random.randn(3,5)
data2

array([[ 1.02157185, -0.38011545,  0.54431081,  0.39298116, -1.35271342],
       [-0.79610225,  2.06612149,  0.63269727, -1.48709871,  2.19499326],
       [ 0.27508139,  1.83063057, -0.77837012,  0.35064661,  0.63123317]])

In [ ]:
# 요소의 평균구하기
np.mean(data2)

np.float64(0.34305784209705836)

In [112]:
np.mean(data2, axis=0)

array([ 0.16685033,  1.1722122 ,  0.13287932, -0.24782365,  0.491171  ])

In [113]:
np.mean(data2, axis=1)


array([0.04520699, 0.52212221, 0.46184432])

In [114]:
np.min(data2)

np.float64(-1.4870987060594807)

In [115]:
#요소의 가장 작은 값 구하기, 반대는, max

np.min(data2, axis=1)

array([-1.35271342, -1.48709871, -0.77837012])

In [127]:
# 표준편차 계산
np.std(data2)

np.float64(1.113249167377242)

In [128]:
# 분산 계산
np.var(data2)

np.float64(1.2393237086661224)

In [129]:
np.sort(data2)[::-1]

array([[-0.77837012,  0.27508139,  0.35064661,  0.63123317,  1.83063057],
       [-1.48709871, -0.79610225,  0.63269727,  2.06612149,  2.19499326],
       [-1.35271342, -0.38011545,  0.39298116,  0.54431081,  1.02157185]])

In [130]:
np.sort(data2, axis=0)

array([[-0.79610225, -0.38011545, -0.77837012, -1.48709871, -1.35271342],
       [ 0.27508139,  1.83063057,  0.54431081,  0.35064661,  0.63123317],
       [ 1.02157185,  2.06612149,  0.63269727,  0.39298116,  2.19499326]])

In [ ]:
# np를 이용하여 다음을 구하라.
# 각 학생의 평균 점수를 구하라.
# 성적이 가장 안정적인 학생을 찾으시오. (표준편차가 낮은 학생)
# 80점 이상의 과목수가 가장 많은 학생의 점수를 나열하시오.

## np.mean( , axis=1) : 평균 점수 계산 (각 행 평균계산)

In [155]:
import numpy as np

# 학생별 성적
scores = np.array([
    [85, 90, 88, 92], [78, 81, 85, 86], [92, 88, 91, 90], [70, 75, 72, 78], [88, 85, 84, 89]])

abc = ['학생1', '학생2', '학생3', '학생4', '학생5']

averages = np.mean(scores, axis=1)    #평균점수계산
for i in range(len(abc)):
    print(abc[i], "평균 점수 :", round(averages[i], 2))

학생1 평균 점수 : 88.75
학생2 평균 점수 : 82.5
학생3 평균 점수 : 90.25
학생4 평균 점수 : 73.75
학생5 평균 점수 : 86.5


## np.std( , axis=1) 표준편차 계산

In [ ]:
std_data0 = np.std(scores, axis=1)    # 표준편차계산
min_std_index = np.argmin(std_data0)

print(f"{abc[min_std_index]} (표준편차: {std_data0[min_std_index]:.2f})")

학생3 (표준편차: 1.48)


## np.sum(scores >= 90, axis=1) 90점 이상 과목 수 계산

In [ ]:
counts90 = np.sum(scores >= 90, axis=1)   # 90점 이상 과목 수 계산
index90 = np.argmax(counts90)

print(f"\n90점 이상 과목 수가 가장 많은 학생: {abc[index90]}")
print(f"{abc[index90]}의 점수: {scores[index90]}")


90점 이상 과목 수가 가장 많은 학생: 학생3
학생3의 점수: [92 88 91 90]
